name: Test package

on: [push]
jobs:

  test-code:
    # This code depends on the result of check-code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pyscholar
      run: |
        python -m pip install -e ".[test]"
    - name: Test with pytest
      run: |
        python -m pytest


    - name: Coverage report
      if: matrix.python-version == '3.10'
      run: |
        python3 -m coverage report | sed 's/^/    /' >> $GITHUB_STEP_SUMMARY
        python3 -m coverage json
        export TOTAL=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
        echo "total=$TOTAL" >> $GITHUB_ENV

    - name: Upload HTML report.
      if: matrix.python-version == '3.10'
      uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: htmlcov
